project:
  type: website

website:
  title: "BRICS"

  navbar:
    left:
      - href: codes/index1.html
        text: Home
      - href: index.qmd
        text: About Me
      - href: info/introduction.qmd
        text: Introduction
      - href: https://github.com/anly501/dsan-5000-project-msheeba4848/tree/main/dsan-website/5000-website
        text: Code
      - href: info/data.qmd
        text: Data
      - href: ""
        text: Data Gathering
        menu: 
          - href: codes/data_gathering_r.ipynb
          - text: Data Gathering - R 
          - href: codes/data_gathering_p.ipynb
          - text: Data Gathering - P 
          - href: codes/record_data.ipynb
            text: Record Data
      - href: ""
        text: Data Cleaning 
        menu:
          - href: codes/data_cleaning_r.ipynb
          - text: Data Cleaning - R
          - href: codes/data_cleaning_p.ipynb
          - text: Data Cleaning - Python
          - href: codes/data_cleaning_record.ipynb
          - text: Data Cleaning - Record Data
      - href: ""
        text: Data Exploration
        menu:
          - href: codes/EDA.ipynb
            text: Exploratory Data Analysis
          - href: codes/naive_bayes.ipynb
            text: Naive Bayes
      - href: codes/clustering.ipynb
        text: Clustering
      - href: codes/dimensionalityreduction.ipynb
        text: Dimensionality Reduction
      - href: ""
        text: Decision Trees
        menu:
          - href: codes/decisiontree_c.ipynb
            text: Classification
          - href: codes/decisiontree_r.ipynb
            text: Regression
      - href: info/conclusion.qmd
        text: Conclusion
    background: white
    foreground: black
    body-footer: footer.qmd
format:
  html:
    theme: journal
    css:  theme.scss
    toc: true



