project:
  type: website

website:
  title: "BRICS"

  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: index1.html
        text: Home
      - href: info/introduction.qmd
        text: Introduction
      - href: https://github.com/anly501/dsan-5000-project-msheeba4848/tree/main/dsan-website/5000-website
        text: Code
      - href: info/data.qmd
        text: Data
      - href: ""
        text: Data Gathering
        menu: 
          - href: codes/data_gathering_r.ipynb
          - text: Data Gathering - R 
          - href: codes/data_gathering_p.ipynb
          - text: Data Gathering - P 
      - href: info/data_cleaning.qmd
        text: Data Cleaning 
      - href: ""
        text: Data Exploration
        menu:
          - href: codes/EDA.ipynb
            text: Exploratory Data Analysis
          - href: codes/naivebayes.ipynb
            text: Naive Bayes
      - href: codes/clustering.ipynb
        text: Clustering
      - href: codes/dimensionalityreduction.ipynb
        text: Dimensionality Reduction
      - href: ""
        text: Decision Trees
        menu:
          - href: codes/decisiontree_c.ipynb
            text: Classification
          - href: codes/decisiontree_r.ipynb
            text: Regression
      - href: info/conclusion.qmd
        text: Conclusion
    background: white
    foreground: black
    body-footer: footer.qmd
format:
  html:
    theme: journal
    css:  theme.scss
    toc: true



