project:
  type: website

website:
  title: "DSAN-5000: Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: info/introduction.qmd
        text: Introduction
        icon: Introduction
      - href: info/code.qmd
        text: Code
      - href: info/data.qmd
        text: Data
      - href: info/introduction.qmd
        text: Introduction
      - href: info/data_gathering.qmd
        text: Data Gathering 
      - href: info/data_cleaning.qmd
        text: Data Cleaning 
      - href: ""
        text: Datqua Exploration
        menu:
          - href: info/data_exploration.qmd
            text: Exploratory Data Analysis
          - href: info/data_exploration.qmd
            text: Naive Bayes

      - href: info/clustering.qmd
        text: Clustering
      - href: info/dimensionality_reduction.qmd
        text: Dimensionality Reduction
    background: white
    foreground: black
    body-footer: footer.qmd

format:
  html:
    theme: morph
    toc: true




