---
title: "Conclusion"
backgroundcolor: white
theme: morph
---


# Down the Road 

Using data from two APIs and the record data from World Bank, the BRICS data has been explored in terms of the questions asked. In addition to that, attempting to do all modelling tasks with pre-defined algorithmns was interesting to witness as it profusely keeps showing us the "no size fits all" trigger. The data has been collected in both textual and quantitative format. For the textual data, the data had been collected from REDDIT API to analyse the sentiments of the users. The record data had a lot of cleaning in terms of pivoting the dataset.Additionally, the data was also cleaned. I learnt about newer ways of cleaning data and analysing it with user-defined functions and the libraries. For textual data, I learnt how to use the PRAW library and SIA() analyser, which I hope to use in the future. 

In terms of data exploration, I understood the importance of data normalisation, and explored various visual techniques within the matplotlib and the seaborn library. It was interesting to see the variabiliy within the countries. The ability to tell stories through visualisation always fasinates me. We tried to explore the scatterplots, the boxplots, countplots and the correlation plots within the dataset. The EDA was limited in nature since my dataset did not consist of categorical datapoints.

During the Naive Bayes, since it is a classifer algorithmn, the GDP growth which was categorised and binned under 'Low Growth', 'Moderate Growth', 'High Growth' and 'Very High Growth'. I hope to look into better literature review and dwelve into more books to find whether GDP could ever be binned. In terms of Naive Bayes, we see that Naive Bayes performs suboptimally or rather less than expected. In terms of the textual data, Naive Bayes performed comparitively better with 63% accuracy on training data and 50% accuracy on testing data in comparison to 28% accuracy for the BRICS' data's training and 13% accuracy on testing data. 

The economic data on unsupervised machine learning algorithmn was also interesting to see, where K-Means, Hierarchial and DBSCAN clustering was performed. I wanted to explore how Clustering would work with a Feature Extraction method such as PCA or t-SNE in terms of their interaction and found that PCA is a better Feature Extraction method than t-SNE for all the three, although the Silhouette Score proves otherwise. I would eventually want to explore more about this too. I learnt the usage of Biplot which gives me an understanding about the PCA in more-depth. Through the outcome was all a lot to catch up on, I learnt about how cluserting works and how to find optimal parameters for clustering that improved the performance of the algorithmns. 

In terms of the Dimensionality Reduction, I learnt where PCA and t-SNE are usually worked. I additionally explored the possibilities when both are combined with one another, that is, PCA with t-SNE and t-SNE with PCA. The outcome wasn't as expected and learnt that we cannot combine both that way.

In terms of Decision Tree and Random Forest, both as a Regressor and a Classifier, I explored the hyperparameter tuning methods of GridSearchCV and RandomisedSearchCV. For the regression, RandomisedSearchCV Random Forest worked better and for classification, Random Forest with GridSearchCV worked better. Though the algorithmns worked, it did not improve the predictive capabilities for the economic data as the model kept performing suboptimally or over-fitting constantly. 

# Have the Questions been answered? 

Intially, there were a lot of questions within the BRICS nations I wanted to explore but for the sake of timeline and this project, the questions have been simple. 

The general opinion within the Reddit seemed generally positive which needs to be looked into with caution but the SIA also labelled almost 50% of the data positively, which was interesting to look at. With words such as 'agenda', 'action','aim' it positive positive. I'd however explore why 'washington', 'argentina', and 'iran' were used.

In general, US is considered to be a hegemonic nation with a greater military power but India's military expenditure has reduced over a period of tie, where as Russia's stayed constant and then increased post 2010. When the GDP for South Africa was the highest, their military expenditure was the lowest. When you compare Russia, their GDP growth was constant but their military expenditure was the highest. It needs to looked into with more parameters but clustering aspect of that showcased interesting clustering with military expenditure. It is interesting to see clusters between Export Import Growth and Military Expenditure. The Services in terms of GDP and the FDI Net Inflows were also highly correlated.

The highly correlated variables in the dataset were Short Term Debt Total Reserves and Adjusted Net National Incomes. Another was Final Consumption Expenditure in terms of Export calculated in terms of GDP and the goods imported in terms of the Balance of Payments. Even the inflation and the lending interest rate were positively correlated. In terms of the negative correlation, final consumption expenditure in terms of GDP and the FDI Net Inflows, Final Consumption Expenditure in terms of GDP and the Imports of Goods and Services's Growth were also negatively related.


The inflation in terms of the BRICS nations, you see South Africa and Brazil having higher bouts of inflation than China or India. Brazil and South Africa suffer from higher rates of inflation, which is a sign of structural problems, political unpredictability, and economic instability. These countries are more vulnerable to pressure from the inside and outside due to issues like high public debt and currency depreciation. Their trade relations and commodity prices, among other geopolitical factors, further influence their economic environment. In contrast, the stable and diverse economies of China and India are reflected in their lower rates of inflation. China's economy is resilient in part because of its controlled economic policies and prominence in international trade. Regional geopolitics, demographic trends, and domestic policies all have an impact on India's vast and diverse economy. Examining the differences in inflation highlights the complex relationship between sustainable development and geopolitical environments and the state of the economy. 

In terms of each countries' Trade GDP, we see Russia performing better than Brazil and South Africa which a linear growth as it is increasing at an increasing rate. In terms of China, it's trade % of the GDP has been positively rising. India, due to it's economic crisis and the flush of trade borders opening emphasised on more international trade than it's other counter-parts during that time. When you look at Brazil, Brazil's influx of trade was more in the early 1990's and it casually decreased. In terms of South Africa, you see it's trade was completely closed in the 1980s due to its dependency on other natures with not have much resources to trade, but over a period of time, that changed.

India's Adjusted Net National Income (ANNI) variability at constant rates is greater than China's implies that India's economic performance exhibits more notable variations over time. This could be the result of a number of things, including modifications to policies, economic reforms, and outside forces affecting the stability of India's economy. China's economy, on the other hand, seems to be performing somewhat more steadily at constant rates, with less noticeable swings.

China's export and import growth rates for goods and services show a steady and dependable trend, which is indicative of its strong manufacturing sector, export-oriented economy, and strategic trade partnerships. However, there is more variation in these rates in South Africa, indicating that the country is more vulnerable to outside influences such as changes in the price of commodities and economic difficulties. The observed variability is a result of South Africa's reliance on resources, currency volatility, and geopolitical uncertainties. The aforementioned comparison highlights the economic robustness and stability of China's trade dynamics, underscoring the importance of taking into account a variety of factors that influence each nation's trade performance.

In terms of the Short Term Debt Reserves, it is correlated in all the countries to other variables except China. This distinct pattern implies that short-term debt reserves in China may not be impacted by the same factors or follow the same trends as those in other nations. This discrepancy may be caused by China's financial methods, economic policies, and substantial foreign exchange reserve

The GDP Growth in comparison to the US and BRICS showcases the movement between a developed and emerging economies. Most of the countries are in the process of becoming developed but South Africa's growth is higher in 2020. This helps us understand and stress on the fact that though visualisation tells us interesting things about the data, the base nuance is also important to look that. Looking at this data, non-economists would comment on US' performance as basic and "needs improvement" but knowing the historical and behaviourial aspects of the country in terms of development is important to consider.


# Miles to Go Before I sleep

BRICS in itself is a very interesting topic and I do intend to work on it in the future. 

The entire strech of the the data pipeline has been a long, yet wonderful journey to somebody that comes from a non-data science background. I am thankful for the support of all the professors and the wifi connection of Georgetown and T-Mobile for relentlessly supporting me throughout. 
